import collar from "../../assets/products/collar.png"
import brush from "../../assets/products/brush.png"
import mouse from "../../assets/products/mouse.png"
import grooming from "../../assets/products/grooming.png"
import catFood from "../../assets/products/cat-food.png"
import toy from "../../assets/products/toy.png"


export const MOCK_DATA = [
    {id:1, nombre: "PRODUCTO 1",descripcion:"khveuigher", precio:1500 ,img:collar},
    {id:2, nombre: "PRODUCTO 2",descripcion:"khveuigher", precio:1500 ,img:brush},
    {id:3, nombre: "PRODUCTO 3",descripcion:"khveuigher", precio:1500 ,img:mouse},
    {id:4, nombre: "PRODUCTO 4",descripcion:"khveuigher", precio:1500 ,img:grooming},
    {id:5, nombre: "PRODUCTO 5",descripcion:"khveuigher", precio:1500 ,img:catFood},
    {id:6, nombre: "PRODUCTO 5",descripcion:"khveuigher", precio:1500 ,img:toy}
]
